### ISSUE TITLE
Install test failure, Ubuntu 20.04 

### ISSUE THREAD

**Issue by Michael-S** [croservices/cro-tls#3] opened 2020-08-03 16:12 UTC
When I try to install on Ubuntu 20.04 I get this error:
[Cro::TLS] Failed to import t/certs-and-keys/server-crt.pem as PEM/ASN1/PKCS12
[Cro::TLS]   in block  at /home/myuser/.rakubrew/versions/moar-2020.07/share/perl6/site/sources/E8D621D9D8A97A8121C098D5D921B58F9E9BE4F9 (IO::Socket::Async::SSL) line 480
[Cro::TLS]   in block  at /home/myuser/.rakubrew/versions/moar-2020.07/share/perl6/site/sources/E8D621D9D8A97A8121C098D5D921B58F9E9BE4F9 (IO::Socket::Async::SSL) line 459
[Cro::TLS]   in block <unit> at t/tls.t line 37

**Comment by japhb** [comment] 2020-09-05 01:50
I'm getting a similar error using these test certs in my own Cro-based code:

```
Failed to import [local-path]/resources/fake-tls/server-crt.pem as PEM/ASN1/PKCS12
  in block  at [install-path]/rakudo-moar-2020.08.2-49-g49f3d433c/install/share/perl6/site/sources/E8D621D9D8A97A8121C098D5D921B58F9E9BE4F9 (IO::Socket::Async::SSL) line 480
  in block  at [install-path]/rakudo-moar-2020.08.2-49-g49f3d433c/install/share/perl6/site/sources/E8D621D9D8A97A8121C098D5D921B58F9E9BE4F9 (IO::Socket::Async::SSL) line 459
  in method start at [install-path]/rakudo-moar-2020.08.2-49-g49f3d433c/install/share/perl6/site/sources/972E1CBA844B858B3B519247881C9F66B8BF629C (Cro::Service) line 6
```

This worked with the same code (and same test certs) as of a couple months ago, and I'm not sure what of the many things that have been upgraded since then caused the problem.  Also, to be clear, `openssl x509 -in resources/fake-tls/server-crt.pem -text` still seems to understand the cert that `IO::Socket::Async::SSL` is complaining about perfectly fine.

I directly installed `IO::Socket::Async::SSL` using the GitHub repo URL to get the blead commit, since the released version has the DH size bug.  (Note that I did also try it with the release version, and even if I ignore the DH test failure and force the install, it still gives the above "Failed to import" error.)  Here's how Zef sees it now:

```
$ zef info IO::Socket::Async::SSL
- Info for: IO::Socket::Async::SSL
- Identity: IO::Socket::Async::SSL:ver<0.7.5>
- Recommended By: Zef::Repository::Ecosystems<cpan>
- Installed: Yes, as IO::Socket::Async::SSL:ver<0.7.5>:auth<jnthn>
Description:	 Provides an API like IO::Socket::Async, but with SSL support.
License:	 Artistic-2.0
Source-url:	 http://www.cpan.org/authors/id/J/JN/JNTHN/Perl6/IO-Socket-Async-SSL-0.7.5.tar.gz
Provides: 1 modules
Support:
#   source:	https://github.com/jnthn/p6-io-socket-async-ssl.git
Depends: 1 items
```

For completeness, here are my Rakudo, Zef, and OS versions:

```
$ raku -v
This is Rakudo version 2020.08.2-49-g49f3d433c built on MoarVM version 2020.08-77-g51d399cb5
implementing Raku 6.d.

$ zef --version
v0.8.5

$ cat /etc/os-release
NAME="Linux Mint"
VERSION="20 (Ulyana)"
ID=linuxmint
ID_LIKE=ubuntu
PRETTY_NAME="Linux Mint 20"
VERSION_ID="20"
HOME_URL="https://www.linuxmint.com/"
SUPPORT_URL="https://forums.ubuntu.com/"
BUG_REPORT_URL="http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/"
PRIVACY_POLICY_URL="https://www.linuxmint.com/"
VERSION_CODENAME=ulyana
UBUNTU_CODENAME=focal
```

**Comment by japhb** [comment] 2020-09-05 04:53
OK, I've now tried building everything on top of older Rakudos as well -- 2020.07 and 2020.06 -- and neither one seemed to change anything.  :-(

**Comment by JJ** [comment] 2020-10-02 08:14
Same error here...

**Comment by japhb** [comment] 2020-10-20 21:55
Still there with a Rakudo built today (2020-10-20, v2020.09-77-gbae905ef6), with IO::Socket::Async::SSL directly installed from GitHub to get latest fixes, and all Cro modules installed from up-to-date source.

Also, it looks like this is the underlying bug for https://github.com/croservices/cro-http/issues/111 as well.

**Comment by Altai-man** [comment] 2020-10-21 07:26
So it's not a rakudo, not cro::tls, since there are no new commits since February, maybe openssl/libressl version?

**Comment by Michael-S** [comment] 2020-10-21 12:15
@japhb  if you install IO::Async::SSL from Github, does zef use that version?  I thought it would still use the one that was configured as a cro-tls dependency and ignore your local version.

**Comment by japhb** [comment] 2020-10-21 16:57
Altai-man: Taking a step back, it's potentially a problem with the test certs not having been regenerated since https://github.com/jnthn/p6-io-socket-async-ssl/issues/56 was fixed -- the test certs date from January, but the fix for `OPENSSL_TLS_SECURITY_LEVEL=2` only merged in July.  Given that that bug specifically mentioned Ubuntu 20.04 support, I wonder if just regenerating the Cro::TLS test certs with a new IO::Socket::Async::SSL and the appropriate new lengths would do the trick.

Michael-S: The last actual version bump of IO::Socket::Async::SSL was last November.  So even though the module installed from Github is a new Git *revision*, it's still the same Rakudo-visible *version*.

**Comment by japhb** [comment] 2020-10-23 17:16
Altai-man: It looks like you did the last cert regen.  Could you do so again?  And could you document the steps you use so we can make working certs of our own the same way -- and thus both get as close as possible to reproducibility (recognizing that of course we'd never be able to reproduce them byte-for-byte) and enable us to easily work around this problem in the future?

**Comment by Altai-man** [comment] 2020-10-24 06:57
@japhb hi. https://gist.github.com/Altai-man/17a30b60ad9350f7f0a1641798131bf5 <- this is the script used to generate test certs, can you please check it?

**Comment by japhb** [comment] 2020-10-25 02:43
@Altai-man Added several comments on that gist.  :-)

**Comment by japhb** [comment] 2020-10-25 04:36
OK, looks like I've got a modified version of your scripts that works locally on my Linux Mint system (which is based on Ubuntu, thus had the Ubuntu and Debian issues) -- see the updated comments on your gist.  Would you like me to PR my version?  (And if so, PR the fixed script and conf only, or those *plus* the working certs generated on my machine with current OpenSSL?)

**Comment by japhb** [comment] 2020-10-25 17:20
As per comment on [Altai-man's gist](https://gist.github.com/Altai-man/17a30b60ad9350f7f0a1641798131bf5), I've created https://github.com/croservices/cro-tls/pull/4 to add the latest version of the TLS cert regen scripts.  Once that's accepted, Altai-man can run them, upload the new certs, spin a release, and Cro::TLS should be installing properly again.

**Comment by Altai-man** [comment] 2020-10-28 11:15
We need a 0.8.4 release before we close this, but fix is on master, @japhb++ for the investigation and fixing the case.

**Comment by japhb** [comment] 2020-12-13 23:37
Should be closable now, since there was a 0.8.4 release?

**Comment by jnthn** [comment] 2020-12-13 23:46
@japhb Yes; thanks for noticing.

**Closed as completed by jnthn** 2020-12-13 23:46 UTC
